### PR TITLE
Restore all pipeline CI jobs

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by cosurgi** [comment]
@ckormanyos you might want revert my commit: 1a5d54b945c27f5bd8355fa480faeef6adfd8162
It is very likely that this commit is what broke the tests, since I have rather little experience with jamfiles.

I think I might have used the colon separators `:` in a single line incorrectly.

**Comment by ckormanyos** [comment]
> is what broke the tests, since I have rather little experience with jamfiles

Hi @cosurgi me too, I share that situation and also am weak on jam files.

Somehow together we seem to be able to get enough, but it's tough going, with lots of iterations as we go along.

I think your scripting in jam was OK. I have a fix cycling now with the GCC/quadmath tests running in test suite `fft` and one single non-quadmath file running in test suite `fft_all`. I will push that CI stuff actually to develop.

**Comment by ckormanyos** [comment]
Hi @cosurgi and @Lagrang3 

OK. I have finally fixed CI. The tests needing quadmath run in test suite `fft` with GCC only. One single non-quadmath test runs with both GCC/clang test suite `fft_all`. In the `fft_all` test suite, a unique executable/object file name is needed with ths suffix `_all` as seen near the end of the entry in the jam file.

You can merge this CI from develop to your branch(es) and add the files you need.

**Comment by cosurgi** [comment]
Awesome! Thank you very much :)

**Pull request merged**
