### PR TITLE
Try adding more CI tests in MSVC

### PR DESCRIPTION
**Pull request by cosurgi**

### CODE REVIEW

**Comment by cosurgi** [comment]
@ckormanyos this branch `fft_janek` is rebased on `fft_chris` so I have your latest stuff.

But it is not rebased on `1_over_N`, I am not sure if @Lagrang3 will add more stuff there.

It is just a note so that we don't miss any commits.

**Comment by cosurgi** [comment]
Oops, we now have this error:

```
fft_correctedness.cpp(73): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1468)
```

**Comment by ckormanyos** [comment]
> we now have this error:

```
fft_correctedness.cpp(73): fatal error C1001: An internal error 
```

That is a tough one. The compiler's lexical parser crashed internally, itself, with no diagnostics whatsoever. The code is probably fine.

Unfortunately, it's on 14.0 (which i do not have set up at the moment). I have seen this kind of thing a lot, however, so I'll take a look.

Basically, I see if I can determine if it's in header or cpp. Then I do a binary search via `#if 0`/`#endif` sectioning within the offending file itself to narrow down the offending lines themselves (or what makes the compiler crash internally).

After all that... We re-write the lines that the legacy compiler can't deal with.

This must be done because msvc 14.0 is mandatory for us. i will dive into it.

Cc: @cosurgi and @Lagrang3

**Comment by cosurgi** [comment]
@ckormanyos  To avoid a third PR please feel free to push to my branch in this PR. I am routinely `git pull`ing on my end.

**Comment by ckormanyos** [comment]
Hi @cosurgi 

Yes, please feel free to simply comment out the file that causes `fatal error C1001`. There is literally **zero** development content in dealing with that --- less than zero actually. If anyone spends time on it, I'll do it within the context of my administrative duties in the project.

Full speed ahead on the actual development...

**Review by ckormanyos — APPROVED** [review]
As you probably suspect, I also feel like the original code was right in my opinion. But one of the compilers did not comprehend it. I ran across several of these cases recently and decided to simply modify the code exactly the way you have done so as a workaround for the legacy msvc 14.0 compiler.

**Comment by cosurgi** [comment]
Yes, thank you for having a look at these small changes.

**Comment by cosurgi** [comment]
@Lagrang3 should `fft_ex06.cpp` work the same when replacing `fftw_rfft` with `gsl_rfft` or `bsl_rfft`? It could be used for msvc tests then.

**Review by Lagrang3 — APPROVED** [review]

**Comment by ckormanyos** [comment]
Hi @cosurgi and @Lagrang3 I would like to get these added CI files for msvc into develop of the fork.

May I merge to develop of the fork?

**Comment by Lagrang3** [comment]
> @Lagrang3 should `fft_ex06.cpp` work the same when replacing `fftw_rfft` with `gsl_rfft` or `bsl_rfft`? It could be used for msvc tests then.

@cosurgi yes.

**Comment by Lagrang3** [comment]
> Hi @cosurgi and @Lagrang3 I would like to get these added CI files for msvc into develop of the fork.
> 
> May I merge to develop of the fork?

To me yes.

**Comment by ckormanyos** [comment]
There are a few trivial warnings in CI on msvc that I will deal with (when also trying to deal with `misc 1001` crash).

For now, we get these tests into develop. CI is cycling. Looks good...

**Comment by cosurgi** [comment]
> For now, we get these tests into develop. CI is cycling. Looks good...

This is great. We are steadily moving forward.

> > @Lagrang3 should fft_ex06.cpp work the same when replacing fftw_rfft with gsl_rfft or bsl_rfft? It could be used for msvc tests then.

> @cosurgi yes.

OK, let's try that in next PR.

**Pull request merged**
